#!/bin/bash
_lvk=$(wget -qO- sshplus.xyz/script/versao)
IP=$(wget -qO- ipv4.icanhazip.com/)
IP2=$(wget -qO- http://whatismyip.akamai.com/)
[[ "$IP" != "$IP2" ]] && ipdovps="$IP2" || ipdovps="$IP"
echo -e "$ipdovps" > /etc/IP
rm -rf /etc/SSHPlus/bot /etc/SSHPlus/ShellBot.sh /etc/SSHPlus/cabecalho /etc/SSHPlus/proxy.py > /dev/null 2>&1
echo -e "America/Sao_Paulo" > /etc/timezone
ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime > /dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata > /dev/null 2>&1
echo -e 'by: MASTER' > /usr/lib/sshplus && cat /usr/lib/sshplus > /usr/lib/licence
[[ ! -d /etc/SSHPlus ]] && mkdir /etc/SSHPlus
[[ ! -d /etc/SSHPlus/senha ]] && mkdir /etc/SSHPlus/senha
[[ ! -e /etc/SSHPlus/Exp ]] && touch /etc/SSHPlus/Exp
[[ ! -d /etc/SSHPlus/userteste ]] && mkdir /etc/SSHPlus/userteste
netstat -nplt| grep -w 'apache2' |grep -w '80' && sed -i "s/Listen 80/Listen 81/g" /etc/apache2/ports.conf && service apache2 restart
[[ "$(grep -o '#Port 22' /etc/ssh/sshd_config)" == "#Port 22" ]] && sed -i "s;#Port 22;Port 22;" /etc/ssh/sshd_config && service ssh restart
grep -v "^PasswordAuthentication" /etc/ssh/sshd_config > /tmp/passlogin && mv /tmp/passlogin /etc/ssh/sshd_config
echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
service ssh restart

wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/addhost.sh?token=AQZXDJ6H7R7FOXBRBADTVNK7JPHCY > /dev/null 2>&1
chmod +x /bin/addhost
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/ajuda.sh?token=AQZXDJ6BDU7B2DIMCP7PGNC7JPHJK > /dev/null 2>&1
chmod +x /bin/ajuda
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/alterarlimite.sh?token=AQZXDJ7ER4VX4MUCN3ISP727JPHLC > /dev/null 2>&1
chmod +x /bin/alterarlimite
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/alterarsenha.sh?token=AQZXDJ5J7XTAIXPZKN4YRYS7JPHNA -O /bin/alterarsenha > /dev/null 2>&1
chmod +x /bin/alterarsenha
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/attscript.sh?token=AQZXDJ5RLYAENGKJ6LZKROK7JPHQ6 -O /bin/attscript > /dev/null 2>&1
chmod +x /bin/attscript
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/badvpn.sh?token=AQZXDJ4ZO3ZATW6JWYTUWDK7JPHTG -O /bin/badvpn > /dev/null 2>&1
chmod +x /bin/badvpn
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/banner.sh?token=AQZXDJ77YZHMMZA2UNLANOS7JPHU6 -O /bin/banner > /dev/null 2>&1
chmod +x /bin/banner
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/blockt.sh?token=AQZXDJ2XFGUTAXPKFSINGFS7JPHW6 -O /bin/blockt > /dev/null 2>&1
chmod +x /bin/blockt
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/botssh.sh?token=AQZXDJ3AOCY666CWW6L6W7K7JPHZE -O /bin/botssh > /dev/null 2>&1
chmod +x /bin/botssh
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/conexao.sh?token=AQZXDJ5ZNCNDMSSSDLPOGXS7JPH4O -O /bin/conexao > /dev/null 2>&1
chmod +x /bin/conexao
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/criarteste.sh?token=AQZXDJ7AE2Q23BRGMX6726K7JPH7U -O /bin/criarteste > /dev/null 2>&1
chmod +x /bin/criarteste
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/criarusuario.sh?token=AQZXDJZZSKO4EQICELVGFJK7JPIB4 -O /bin/criarusuario > /dev/null 2>&1
chmod +x /bin/criarusuario
wget https://github.com/Masterskjsj/ajannsbszbJ/blob/master/Modulos/delhost.sh -O /bin/delhost > /dev/null 2>&1
chmod +x /bin/delhost
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/delscript.sh?token=AQZXDJ3DFR7PCYBO6CT4I2C7JPIIE -O /bin/delscript > /dev/null 2>&1
chmod +x /bin/delscript
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/detalhes.sh?token=AQZXDJ4HH23RFBTTJJ3E2227JPIKG -O /bin/detalhes > /dev/null 2>&1
chmod +x /bin/detalhes
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/droplimiter.sh?token=AQZXDJ4ZQZNXFCSE5TQ5I7K7JPIOQ -O /bin/droplimiter > /dev/null 2>&1
chmod +x /bin/droplimiter
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/expcleaner.sh?token=AQZXDJ6MFQIVPV3RG3X3L2S7JPIQY -O /bin/expcleaner > /dev/null 2>&1
chmod +x /bin/expcleaner
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/infousers.sh?token=AQZXDJ5MQYWGOL6TND6NAD27JPITM -O /bin/infousers > /dev/null 2>&1
chmod +x /bin/infousers
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/limiter.sh?token=AQZXDJY4ZXYXURU3BW7N6QS7JPJIO -O /bin/limiter > /dev/null 2>&1
chmod +x /bin/limiter
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/menu.sh?token=AQZXDJ3J4FVD3T3Q2NLJN6K7JPJKO -O /bin/menu > /dev/null 2>&1
chmod +x /bin/menu
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/mudardata.sh?token=AQZXDJ3E54JHOKMUE3NY25C7JPJOK -O /bin/mudardata > /dev/null 2>&1
chmod +x /bin/mudardata
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/otimizar.sh?token=AQZXDJ4ICDTTOI27D43P2GS7JPJR2 -O /bin/otimizar > /dev/null 2>&1
chmod +x /bin/otimizar
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/reiniciarservicos.sh?token=AQZXDJ5IBBHA6S3ISQP464S7JPJUQ -O /bin/reiniciarservicos > /dev/null 2>&1
chmod +x /bin/reiniciarservicos
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/reiniciarsistema.sh?token=AQZXDJ7CK7LGBTZZYY6JYHK7JPJXM -O /bin/reiniciarsistema > /dev/null 2>&1
chmod +x /bin/reiniciarsistema
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/remover.sh?token=AQZXDJZ6XWXR4DQGJT6LYC27JPJZK -O /bin/remover > /dev/null 2>&1
chmod +x /bin/remover
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/senharoot.sh?token=AQZXDJYMMROF3AOJEDKGX5S7JPJ3K -O /bin/senharoot > /dev/null 2>&1
chmod +x /bin/senharoot
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/speedtest.sh?token=AQZXDJ4HOR65PVXO6RWBUOC7JPJ5E -O /bin/speedtest > /dev/null 2>&1
chmod +x /bin/speedtest
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/sshmonitor.sh?token=AQZXDJ7NN7JPDCCE7WYZAGK7JPJ64 -O /bin/sshmonitor > /dev/null 2>&1
chmod +x /bin/sshmonitor
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/uexpired.sh?token=AQZXDJ6QKGOJRKPJ7TWJVOC7JPKBK -O /bin/uexpired > /dev/null 2>&1
chmod +x /bin/uexpired
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/userbackup.sh?token=AQZXDJYR7R5APXITHLAF63K7JPKDW -O /bin/userbackup > /dev/null 2>&1
chmod +x /bin/userbackup
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/verifbot.sh?token=AQZXDJ3DPWVHOOPQNRL3DAC7JPKIO -O /bin/verifbot > /dev/null 2>&1
chmod +x /bin/verifbot
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/verifatt.sh?token=AQZXDJ7NDAFQRB3ZYVSHLNC7JPKFQ -O /bin/verifatt > /dev/null 2>&1
chmod +x /bin/verifatt
wget https://raw.githubusercontent.com/Erikii/mashhhhshsh/master/Modulos/bot.sh -O /etc/SSHPlus/bot > /dev/null 2>&1
chmod +x /etc/SSHPlus/bot
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/cabecalho.sh?token=AQZXDJZUV4ZDZRSJJZKHSU27JPKKS -O /etc/SSHPlus/cabecalho > /dev/null 2>&1
chmod +x /etc/SSHPlus/cabecalho
wget https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/Modulos/proxy.py?token=AQZXDJZXH7JA4XHXHKVL26K7JPKM2 -O /etc/SSHPlus/proxy.py > /dev/null 2>&1
chmod +x /etc/SSHPlus/proxy.py

[[ ! -d /etc/bot ]] && mkdir /etc/bot
[[ ! -d /etc/bot/info-users ]] && mkdir /etc/bot/info-users
[[ ! -d /etc/bot/arquivos ]] && mkdir /etc/bot/arquivos
[[ ! -d /etc/bot/revenda ]] && mkdir /etc/bot/revenda
[[ ! -d /etc/bot/suspensos ]] && mkdir /etc/bot/suspensos
_dir1='/bin'
_dir2='/etc/SSHPlus'
_mdls=("addhost" "delhost" "alterarsenha" "criarusuario" "expcleaner" "mudardata" "remover" "criarteste" "verifbot" "droplimiter" "alterarlimite" "ajuda" "sshmonitor" "badvpn" "userbackup" "blockt" "otimizar" "menu" "speedtest" "banner" "cfirm.py" "senharoot" "reiniciarservicos" "reiniciarsistema" "attscript" "conexao" "delscript" "detalhes" "botssh" "infousers" "verifatt" "limiter" "uexpired" "cabecalho" "bot" "proxy.py")
_arq_host="/etc/hosts"
_host[0]="d1n212ccp6ldpw.cloudfront.net"
_host[1]="dns.whatsapp.net"
_host[2]="portalrecarga.vivo.com.br/recarga"
_host[3]="navegue.vivo.com.br/controle/"
_host[4]="navegue.vivo.com.br/pre/"
_host[5]="www.whatsapp.net"
_host[6]="/SSHPLUS?"
for host in ${_host[@]}; do
	if [[ "$(grep -w "$host" $_arq_host | wc -l)" = "0" ]]; then
		sed -i "3i\127.0.0.1 $host" $_arq_host
	fi
done
crontab -r
[[ ! -e /etc/autostart ]] && {
echo '#!/bin/bash
clear
#INICIO AUTOMATICO' > /etc/autostart
chmod +x /etc/autostart
} || {
[[ $(ps x | grep "bot_plus"|grep -v grep | wc -l) != '0' ]] && wget -qO- https://raw.githubusercontent.com/Masterskjsj/ajannsbszbJ/master/install/ShellBot.sh?token=AQZXDJ6MKU4ZQAP57PE3HC27JPKTE > /etc/SSHPlus/ShellBot.sh
for proc in $(ps x |grep 'dmS'|grep -v 'grep'|awk {'print $1'} ); do
screen -r -S "$proc" -X quit
done
screen -wipe > /dev/null
echo '#!/bin/bash
clear
#INICIO AUTOMATICO' > /etc/autostart
chmod +x /etc/autostart
}
#INICIO
[[ $(crontab -l|grep -c "uexpired") = '0' ]] && (crontab -l 2>/dev/null; echo "0 */6 * * * /bin/uexpired") | crontab -
[[ $(crontab -l|grep -c "verifatt") = '0' ]] && (crontab -l 2>/dev/null; echo "@daily /bin/verifatt") | crontab -
[[ $(crontab -l|grep -c "autostart") = '0' ]] && (crontab -l 2>/dev/null; echo "@reboot /etc/autostart") | crontab -
[[ $(crontab -l|grep -c "autostart") = '1' ]] && (crontab -l 2>/dev/null; echo "* * * * * /etc/autostart") | crontab -
echo "$_lvk" |sed -n '1 p' |cut -d' ' -f2 > /bin/versao && cat /bin/versao > /home/sshplus
service ssh restart > /dev/null 2>&1
[[ -d /var/www/html/openvpn ]] && service apache2 restart > /dev/null 2>&1
rm -rf $home/list > /dev/null 2>&1